psql --username=freecodecamp --dbname=postgres
#Create a number_guess database to hold the information suggested in the user stories
CREATE DATABASE number_guess
\c number_guess
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(22) NOT NULL UNIQUE
);
CREATE TABLE games (
    game_id SERIAL PRIMARY KEY,
    number_of_attempts INT NOT NULL,
    user_id INT REFERENCES users(user_id)
);
